### ISSUE TITLE
schema.json not found

### ISSUE THREAD

**Issue by davidbrochart** [jupyter-server/jupyter_releaser#269]
## Description

I recently had the following [error](https://github.com/jupyter-server/jupyverse/runs/5690961585?check_suite_focus=true):
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/runpy.py", line 1[97](https://github.com/jupyter-server/jupyverse/runs/5690961585?check_suite_focus=true#step:10:97), in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/jupyter_releaser/actions/draft_changelog.py", line 6, in <module>
    from jupyter_releaser.util import CHECKOUT_NAME
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/jupyter_releaser/util.py", line 45, in <module>
    SCHEMA = files("jupyter_releaser").joinpath("schema.json").read_text()
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/pathlib.py", line 1266, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/jupyter_releaser/schema.json'
```

**Comment by blink1073** [comment]
cf #270
