### ISSUE TITLE
jupyter_ydoc release failed

### ISSUE THREAD

**Issue by davidbrochart** [jupyter-server/jupyter_releaser#337]
## Description

While releasing [jupyter_ydoc](https://github.com/jupyter-server/jupyter_ydoc) I got [this error message](https://github.com/davidbrochart/jupyter_releaser/runs/7135879828?check_suite_focus=true):
```
--------------------------------------------------
extract-release
--------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.5/x64/bin/jupyter-releaser", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/runner/work/jupyter_releaser/jupyter_releaser/jupyter_releaser/cli.py", line [99](https://github.com/davidbrochart/jupyter_releaser/runs/7135879828?check_suite_focus=true#step:5:103), in invoke
    super().invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/work/jupyter_releaser/jupyter_releaser/jupyter_releaser/cli.py", line 607, in extract_release
    lib.extract_release(
  File "/home/runner/work/jupyter_releaser/jupyter_releaser/jupyter_releaser/lib.py", line 324, in extract_release
    release = util.release_for_url(gh, release_url)
  File "/home/runner/work/jupyter_releaser/jupyter_releaser/jupyter_releaser/util.py", line 331, in release_for_url
    raise ValueError(f"No release found for url {url}")
ValueError: No release found for url https://github.com/jupyter-server/jupyter_ydoc/releases/tag/untagged-80307bb7ca1ea2dcd99e
```
Not sure what is going on.

**Comment by blink1073** [comment]
Does it work if you put that URL into the "Publish URL" workflow?  I think I've seen something like this before if I mis-typed a repo name with a hyphen vs underscore.

**Comment by davidbrochart** [comment]
Yes, it [worked](https://github.com/davidbrochart/jupyter_releaser/runs/7145401445?check_suite_focus=true).
Weird, it's not the first time I release `jupyter_ydoc` with the releaser.
Thanks!
