### ISSUE TITLE
Error releasing jupyter_server_ydoc

### ISSUE THREAD

**Issue by davidbrochart** [jupyter-server/jupyter_releaser#346]
## Description

While trying to make a [full release of jupyter_server_ydoc](https://github.com/davidbrochart/jupyter_releaser/runs/7273143090?check_suite_focus=true) I got this error message:

<details>

```
--------------------------------------------------
check-changelog
--------------------------------------------------
COMMAND: git --no-pager tag --sort=-creatordate --merged refs/heads/main
v0.1.1
Getting changes to jupyter-server/jupyter_server_ydoc since v0.1.1 on branch main...
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/github_activity/github_activity.py", line 549, in _get_datetime_and_type
    dt = _get_datetime_from_git_ref(org, repo, datetime_or_git_ref, auth)
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/github_activity/github_activity.py", line 568, in _get_datetime_from_git_ref
    response.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/jupyter-server/jupyter_server_ydoc/commits/v0.1.1
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/github_activity/github_activity.py", line 553, in _get_datetime_and_type
    dt = dateutil.parser.parse(datetime_or_git_ref)
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/dateutil/parser/_parser.py", line 643, in parse
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: v0.1.1
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.5/x64/bin/jupyter-releaser", line 8, in <module>
    sys.exit(main())
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/runner/work/jupyter_releaser/jupyter_releaser/jupyter_releaser/cli.py", line 99, in invoke
    super().invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/work/jupyter_releaser/jupyter_releaser/jupyter_releaser/cli.py", line 412, in check_changelog
    changelog.check_entry(
  File "/home/runner/work/jupyter_releaser/jupyter_releaser/jupyter_releaser/changelog.py", line 251, in check_entry
    raw_entry = get_version_entry(
  File "/home/runner/work/jupyter_releaser/jupyter_releaser/jupyter_releaser/changelog.py", line 96, in get_version_entry
    md = generate_activity_md(
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/github_activity/github_activity.py", line 228, in generate_activity_md
    data = get_activity(
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/github_activity/github_activity.py", line 119, in get_activity
    since_dt, since_is_git_ref = _get_datetime_and_type(org, repo, since, auth)
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/site-packages/github_activity/github_activity.py", line 556, in _get_datetime_and_type
    raise ValueError(
ValueError: v0.1.1 not found as a ref or valid date format
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/runner/work/jupyter_releaser/jupyter_releaser/jupyter_releaser/actions/draft_release.py", line 81, in <module>
    run_action("jupyter-releaser check-changelog")
  File "/home/runner/work/jupyter_releaser/jupyter_releaser/jupyter_releaser/actions/common.py", line 36, in run_action
    _run(target, *args, **kwargs)
  File "/home/runner/work/jupyter_releaser/jupyter_releaser/jupyter_releaser/util.py", line 88, in run
    raise e
  File "/home/runner/work/jupyter_releaser/jupyter_releaser/jupyter_releaser/util.py", line 80, in run
    process = tee(cmd, **kwargs)
  File "/home/runner/work/jupyter_releaser/jupyter_releaser/jupyter_releaser/tee.py", line 155, in run
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command 'jupyter-releaser check-changelog' returned non-zero exit status 1.
```

</details>

Not sure if it's because it's the first release or the [changelog](https://github.com/jupyter-server/jupyter_server_ydoc/blob/6d67fd68a17dac05f4755a746e11b035a62430a0/CHANGELOG.md) has an issue?

**Comment by blink1073** [comment]
I think this is related to changes made in #341 or #343.  I have been trying to figure out a way to make all of this work, I think the solution is to drop support for `dev` mode handling until we implement https://github.com/jupyter-server/jupyter_releaser/issues/272#issuecomment-1179777435.

**Comment by blink1073** [comment]
For now you can skip `check-changelog` when you run the workflow (under `Comma separated list of steps to skip`)

**Comment by davidbrochart** [comment]
Thanks, that worked.

**Comment by davidbrochart** [comment]
Note that the [check_release](https://github.com/jupyter-server/jupyter_server_ydoc/runs/7276200332?check_suite_focus=true) fails with:
```
ERROR: No matching distribution found for ypy-websocket>=0.1.23
```
Which is strange because it requires [ypy-websocket>=0.1.13](https://github.com/jupyter-server/jupyter_server_ydoc/blob/db6a568d1041692c3918d690361e356d3bfe837d/pyproject.toml#L25).

**Comment by davidbrochart** [comment]
I tried skipping `check-changelog` and `check-python` but I cannot [release jupyter_server_ydoc](https://github.com/davidbrochart/jupyter_releaser/runs/7277820983?check_suite_focus=true) anymore. I get:
```
ERROR: No matching distribution found for jupyter-ydoc==0.1.23
```
While I require `jupyter_ydoc==0.1.13`.

**Comment by davidbrochart** [comment]
Wow, that was changed by the [by the action](https://github.com/jupyter-server/jupyter_server_ydoc/commit/37c1a6fb7e18834868e7b0f9c2fc58aea58557a0).

**Comment by blink1073** [comment]
Ah, yikes, I'd suggest adding a version template [here](https://github.com/jupyter-server/jupyter_server_ydoc/blob/37c1a6fb7e18834868e7b0f9c2fc58aea58557a0/pyproject.toml#L117) that includes "version ="

**Comment by davidbrochart** [comment]
Closing, as this was fixed.
