### ISSUE TITLE
Draft changelog fails

### ISSUE THREAD

**Issue by davidbrochart** [jupyter-server/jupyter_releaser#385]
## Description

I'm trying to create a Draft Changelog for jupyverse, explicitly specifying a `0.0.40` version, and I get [this error](https://github.com/davidbrochart/jupyter_releaser/actions/runs/3063410743/jobs/4945457478) in "bump-version":
```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.6/x64/bin/hatchling", line 8, in <module>
    sys.exit(hatchling())
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/hatchling/cli/__init__.py", line 26, in hatchling
    command(**kwargs)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/hatchling/cli/version/__init__.py", line 33, in version_impl
    updated_version = metadata.hatch.version.scheme.update(desired_version, original_version, version_data)
  File "/opt/hostedtoolcache/Python/3.10.6/x64/lib/python3.10/site-packages/hatchling/version/scheme/standard.py", line 48, in update
    raise ValueError(
ValueError: Version `0.0.39` is not higher than the original version `0.0.39`
```

**Comment by blink1073** [comment]
Hmm, I see `RH_VERSION_SPEC` is set to `0.0.40` but in `bump-version` it is choosing `0.0.39`

**Comment by blink1073** [comment]
I think we need to add logging to `cli.py` to show what values the command was called with, and whether they were overridden by environment variables.  We'd have to be careful not to output sensitive things like tokens, which would have to be put on a block list.

**Comment by davidbrochart** [comment]
I've released jupyverse successfully, by setting `next` as the new version.

**Comment by blink1073** [comment]
This should be fixed now, we had a bug where we were bumping the version twice

**Comment by jtpio** [comment]
@davidbrochart are you still experiencing this issue, or do you think it could be closed?
